version: '3.8'

services:
  backend:
    image: ghcr.io/danghb/coffee_issue_store/backend:latest
    container_name: issue-collector-backend
    restart: always
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - PORT=3000
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/logs:/app/logs
      # Map the local data/sqlite directory to /app/data in the container
      - ./data/sqlite:/app/data
    ports:
      - "3000:3000"

  nginx:
    image: ghcr.io/danghb/coffee_issue_store/nginx:latest
    container_name: issue-collector-nginx
    restart: always
    ports:
      - "12581:80"
    depends_on:
      - backend
    volumes:
       - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
