version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: issue-collector-backend
    restart: always
    environment:
      # Connect to the mysql service container
      - DATABASE_URL=mysql://root:root@mysql:3306/issue_collector
      - PORT=3000
    volumes:
      # Data persistance for Uploads
      - ./data/uploads:/app/uploads
      # Data persistance for Logs
      - ./data/logs:/app/logs
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: issue-collector-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: issue_collector
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306" # Expose for local development

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: issue-collector-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
       - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
